kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-operator
  labels:
    app: enmasse
    name: iot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: iot-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: iot-operator
    spec:
      serviceAccountName: iot-operator
      containers:
      - name: operator
        image: ${CONTROLLER_MANAGER_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "iot-operator"
        - name: IMAGE_PULL_POLICY
          value: "${IMAGE_PULL_POLICY}"
        - name: CONTROLLER_ENABLE_IOT_PROJECT
          value: "true"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        - name: IOT_AUTH_SERVICE_IMAGE
          value: ${IOT_AUTH_SERVICE_IMAGE}
        - name: IOT_DEVICE_REGISTRY_FILE_IMAGE
          value: ${IOT_DEVICE_REGISTRY_FILE_IMAGE}
        - name: IOT_DEVICE_REGISTRY_INFINISPAN_IMAGE
          value: ${IOT_DEVICE_REGISTRY_INFINISPAN_IMAGE}
        - name: IOT_GC_IMAGE
          value: ${IOT_GC_IMAGE}
        - name: IOT_HTTP_ADAPTER_IMAGE
          value: ${IOT_HTTP_ADAPTER_IMAGE}
        - name: IOT_MQTT_ADAPTER_IMAGE
          value: ${IOT_MQTT_ADAPTER_IMAGE}
        - name: IOT_TENANT_SERVICE_IMAGE
          value: ${IOT_TENANT_SERVICE_IMAGE}
        - name: IOT_PROXY_CONFIGURATOR_IMAGE
          value: ${IOT_PROXY_CONFIGURATOR_IMAGE}
        - name: QDROUTERD_BASE_IMAGE
          value: ${QDROUTERD_BASE_IMAGE}
        - name: NONE_AUTHSERVICE_IMAGE
          value: ${NONE_AUTHSERVICE_IMAGE}
        - name: KEYCLOAK_IMAGE
          value: ${KEYCLOAK_IMAGE}
        - name: KEYCLOAK_PLUGIN_IMAGE
          value: ${KEYCLOAK_PLUGIN_IMAGE}
        resources:
          limits:
            memory: 128Mi
